var searchData=
[
  ['code_20contribution_0',['Your First Code Contribution',['../md_CONTRIBUTING.html#autotoc_md17',1,'']]],
  ['code_20of_20conduct_1',['Code of Conduct',['../md_CONTRIBUTING.html#autotoc_md8',1,'']]],
  ['code_20of_20conduct_20–_20vir_3a_3astdx_3a_3asimd_2',['Code of Conduct – vir::stdx::simd',['../md_CODE__OF__CONDUCT.html',1,'']]],
  ['commit_20messages_3',['Commit Messages',['../md_CONTRIBUTING.html#autotoc_md20',1,'']]],
  ['concepts_4',['Concepts',['../md_README.html#autotoc_md40',1,'']]],
  ['conduct_5',['Code of Conduct',['../md_CONTRIBUTING.html#autotoc_md8',1,'']]],
  ['conduct_20–_20vir_3a_3astdx_3a_3asimd_6',['Code of Conduct – vir::stdx::simd',['../md_CODE__OF__CONDUCT.html',1,'']]],
  ['constant_20expressions_7',['&lt;tt&gt;constexpr_wrapper&lt;/tt&gt;: function arguments as constant expressions',['../md_README.html#autotoc_md43',1,'']]],
  ['constants_8',['Simple iota &lt;tt&gt;simd&lt;/tt&gt; constants',['../md_README.html#autotoc_md29',1,'']]],
  ['constexpr_5fwrapper_9',['constexpr_wrapper',['../structvir_1_1constexpr__wrapper.html',1,'vir']]],
  ['constexpr_5fwrapper_20tt_20_3a_20function_20arguments_20as_20constant_20expressions_10',['&lt;tt&gt;constexpr_wrapper&lt;/tt&gt;: function arguments as constant expressions',['../md_README.html#autotoc_md43',1,'']]],
  ['constexpr_5fwrapper_3c_201_20_3e_11',['constexpr_wrapper&lt; 1 &gt;',['../structvir_1_1constexpr__wrapper.html',1,'vir']]],
  ['constexpr_5fwrapper_3c_20alignof_28typename_20v_3a_3avalue_5ftype_29_3e_12',['constexpr_wrapper&lt; alignof(typename V::value_type)&gt;',['../structvir_1_1constexpr__wrapper.html',1,'vir']]],
  ['constexpr_5fwrapper_3c_20v_3a_3atemplate_20memory_5falignment_3c_20t_20_3e_20_3e_13',['constexpr_wrapper&lt; V::template memory_alignment&lt; T &gt; &gt;',['../structvir_1_1constexpr__wrapper.html',1,'vir']]],
  ['contents_14',['Contents',['../md_CONTRIBUTING.html#autotoc_md7',1,'Table of Contents'],['../md_README.html#autotoc_md24',1,'Table of Contents']]],
  ['contiguous_5fiterator_15',['contiguous_iterator',['https://en.cppreference.com/w/cpp/iterator/contiguous_iterator.html',1,'std']]],
  ['contiguous_5frange_16',['contiguous_range',['https://en.cppreference.com/w/cpp/ranges/contiguous_range.html',1,'std::ranges']]],
  ['contribute_17',['I Want To Contribute',['../md_CONTRIBUTING.html#autotoc_md10',1,'']]],
  ['contributing_20to_20vir_3a_3astdx_3a_3asimd_18',['Contributing to vir::stdx::simd',['../md_CONTRIBUTING.html',1,'']]],
  ['contribution_19',['Your First Code Contribution',['../md_CONTRIBUTING.html#autotoc_md17',1,'']]],
  ['convenient_20',['Making &lt;tt&gt;simd&lt;/tt&gt; conversions more convenient',['../md_README.html#autotoc_md30',1,'']]],
  ['conversion_20between_20tt_20std_3a_3abitset_20tt_20and_20tt_20simd_5fmask_20tt_21',['Conversion between &lt;tt&gt;std::bitset&lt;/tt&gt; and &lt;tt&gt;simd_mask&lt;/tt&gt;',['../md_README.html#autotoc_md37',1,'']]],
  ['conversions_20more_20convenient_22',['Making &lt;tt&gt;simd&lt;/tt&gt; conversions more convenient',['../md_README.html#autotoc_md30',1,'']]],
  ['copy_5fto_23',['copy_to',['../classvir_1_1simd__tuple_3_01T_00_01N_01_4.html#a36f874c569952fda502ff1c83b96a0e4',1,'vir::simd_tuple&lt; T, N &gt;::copy_to()'],['../classvir_1_1vectorized__struct_3_01T_00_01N_01_4.html#a08823301e973ee5f0b08553a9586a274',1,'vir::vectorized_struct&lt; T, N &gt;::copy_to()']]],
  ['count_5fif_24',['count_if',['../group__vir__count__if.html',1,'Algorithm: count_if'],['https://en.cppreference.com/w/cpp/algorithm/count_if.html',1,'std::count_if()'],['../group__vir__count__if.html#ga07021695db7f024397c18cb0e4aba81b',1,'vir::count_if(ExecutionPolicy pol, It first, It last, F &amp;&amp;pred)'],['../group__vir__count__if.html#gaabb1ceb863d85db2c1a376b54dfa608e',1,'vir::count_if(ExecutionPolicy pol, R &amp;&amp;rg, F &amp;&amp;pred)'],['../group__vir__count__if.html#ga04e27635680ae107c7579df243ca4fed',1,'std::count_if()']]]
];
