# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright © 2022–2024 GSI Helmholtzzentrum fuer Schwerionenforschung GmbH
#                       Matthias Kretz <m.kretz@gsi.de>

name: Emscripten CI

on:
  push:
    branches: [ master, main ]
    paths:
      - '**.h'
      - '**.cpp'
      - '**.cc'
      - '**.sh'
      - '**Makefile'
      - '**CMakeLists.txt'
      - '.github/workflows/Emscripten.yml'
  pull_request:

jobs:
  emscripten:
    strategy:
      fail-fast: true
      matrix:
        version: [ latest ]

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Install emscripten ${{ matrix.version }}
        run: |
          cd
          git clone --depth=1 https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install ${{ matrix.version }}
          ./emsdk activate ${{ matrix.version }}

      - name: Run test suite
        shell: bash
        env:
          CXX: em++
        run: |
          source ~/emsdk/emsdk_env.sh
          make check DRIVEROPTS=-vvf
